<type>: Munch
<init>: true
# PyTorch Lightning System.
system:
  <type>: MimickingClassification
  <init>: true
  # Model.
  model:
    <type>: get_default_set_transformer
    <init>: true

  # Data loaders.
  train_loader: null
  valid_loader: null
  loaders:
    <type>: get_both_default_mimicking_loaders
    <init>: true
    distribution: "uniform"
    voting_rule|plurality:
      <type>: get_plurality
      <init>: true
    voting_rule|borda:
      <type>: get_borda
      <init>: true
    voting_rule|copeland:
      <type>: get_copeland
      <init>: true
    voting_rule|maximin:
      <type>: get_maximin
      <init>: true
    return_graph: false

  # Optimizer.
  optimizer:
    <type>: Adam
    <init>: false
    lr: 0.0001

  # Learning rate scheduler.
  scheduler_wrapper:
    <type>: TransformerSchedulerWrapper
    <init>: true
    get_fn:
      <type>: get_cosine_schedule_with_warmup
      <init>: false
    num_warmup_steps: 20 # in epochs
    num_training_steps: 20000

  # Loss functions.
  loss_fn:
    <type>: CrossEntropyLoss
    <init>: true

# wandb experiment
logger:
  <type>: WandbLogger
  <init>: false
  project: "lte"
  entity: "byol"
  tags: ["set-transformer", "icml", "mimic", "take-1"]

manage_checkpoint:
  <type>: manage_checkpoint
  <init>: true
  root_path: "/scratch/hdd001/home/jennybao/projects/LTE"
  experiment_name: "mimic"
  load_version: null


trainer:
  <type>: Trainer
  <init>: false
  max_epochs: 20000
  gradient_clip_val: 1.

# Seed.
seed: 0
