<type>: Munch
<init>: true
# PyTorch Lightning System.
system:
  <type>: MimickingClassification
  <init>: true
  # Lawyers.
  model:
    <type>: SetTransformer
    <init>: true
    encoder:
      <type>: SetTransformerEncoder
      <init>: true
      num_heads: 20
      dim_elements: 400   # max_candidates^2 for one-hot
      dim_hidden: 400
      dim_out: 400
      add_layer_norm: true
    decoder:
      <type>: SetTransformerDecoder
      <init>: true
      num_heads: 20
      num_seed_vectors: 20  # max_candidates
      dim_elements: 400
      dim_hidden1: 400
      dim_hidden2: 400
      dim_out: 1
      add_layer_norm: true
  # Data loaders.
  train_loader:
    <type>: DataLoader
    <init>: true
    dataset:
      <type>: Ballot
      <init>: true
      min_num_voters: [50, 80]
      max_num_voters: [69, 99]
      max_num_candidates: 20
      min_num_candidates: 10
      batch_size: 128
      epoch_length: 2048
      voting_rule:
        <type>: get_plurality
        <init>: true
      utility_distribution: "uniform"
      one_hot_candidates: true
    batch_size: 1
    shuffle: true
    num_workers: 0
  valid_loader:
    <type>: DataLoader
    <init>: true
    dataset:
      <type>: Ballot
      <init>: true
      min_num_voters: [20, 40, 150, 200]
      max_num_voters: [29, 109, 159, 209]
      max_num_candidates: 20
      min_num_candidates: 10
      batch_size: 32
      epoch_length: 1024
      voting_rule:
        <type>: get_plurality
        <init>: true
      utility_distribution: "uniform"
      one_hot_candidates: true
    batch_size: 1
    shuffle: true
    num_workers: 0
  optimizer:
    <type>: Adam
    <init>: false
    lr: 0.0001
  # Loss functions.
  loss_fn:
    <type>: CrossEntropyLoss
    <init>: true

# TestTube experiment.
logger:
  <type>: TestTubeLogger
  <init>: false

trainer:
  <type>: Trainer
  <init>: false
  show_progress_bar: true
  early_stop_callback: false
  max_nb_epochs: 100

# Seed.
seed: 0
