<type>: Munch
<init>: true
# PyTorch Lightning System.
system:
  <type>: MimickingClassification
  <init>: true
  # Lawyers.
  model:
    <type>: SetTransformer
    <init>: true
    encoder:
      <type>: SetTransformerEncoder
      <init>: true
      num_heads: 10
      dim_elements: 225   # max_candidates^2 for one-hot
      dim_hidden: 100
      dim_out: 100
      add_layer_norm: false
    decoder:
      <type>: SetTransformerDecoder
      <init>: true
      num_heads: 10
      num_seed_vectors: 15  # max_candidates
      dim_elements: 100
      dim_hidden1: 100
      dim_hidden2: 100
      dim_out: 1
      add_layer_norm: false
  # Data loaders.
  train_loader:
    <type>: DataLoader
    <init>: true
    dataset:
      <type>: Ballot
      <init>: true
      max_num_voters: 79
      min_num_voters: 50
      max_num_candidates: 15
      min_num_candidates: 10
      batch_size: 512
      epoch_length: 2048
      voting_rule:
        <type>: get_plurality
        <init>: true
      utility_distribution: "uniform"
      one_hot_candidates: true
    batch_size: 1
    shuffle: true
    num_workers: 0
  valid_loader:
    <type>: DataLoader
    <init>: true
    dataset:
      <type>: Ballot
      <init>: true
      max_num_voters: 79
      min_num_voters: 50
      max_num_candidates: 15
      min_num_candidates: 10
      batch_size: 256
      epoch_length: 256
      voting_rule:
        <type>: get_plurality
        <init>: true
      utility_distribution: "uniform"
      one_hot_candidates: true
    batch_size: 1
    shuffle: true
    num_workers: 0
  optimizer:
    <type>: Adam
    <init>: false
    lr|lr_0_0001: 0.0001
    lr|lr_0_0003: 0.0003
  # Loss functions.
  loss_fn:
    <type>: CrossEntropyLoss
    <init>: true

# TestTube experiment.
logger:
  <type>: TestTubeLogger
  <init>: false

trainer:
  <type>: Trainer
  <init>: false
  show_progress_bar: true
  early_stop_callback: false
  max_nb_epochs: 125

# Seed.
seed: 0
