<type>: Munch
<init>: true
# PyTorch Lightning System.

system:
  <type>: MimickingClassification
  <init>: true
  # Lawyers.
  model:
    <type>: get_default_gin
    <init>: true
  # Data loaders.
  train_loader:
    <type>: get_default_mimicking_loader
    <init>: true
    distribution: "uniform"
    voting_rule:
      <type>: get_borda
      <init>: true
    return_graph: true

  valid_loader:
    <type>: get_default_mimicking_loader
    <init>: true
    distribution: "uniform"
    voting_rule:
      <type>: get_borda
      <init>: true
    return_graph: true

  optimizer:
    <type>: Lookahead
    <init>: true
    optimizer:
      <type>: Adam
      <init>: false
      lr: 0.01
    k: 5
    alpha: 0.5
  loss_fn:
    <type>: CrossEntropyLoss
    <init>: true
  save_checkpoint: true

# TestTube experiment.
logger:
  <type>: WandbLogger
  <init>: false
  project: "lte"
  entity: "byol"
  tags: ["gin", "mimic_borda", "finalizing", "save_and_load"]

manage_checkpoint:
  <type>: manage_checkpoint
  <init>: true
#  root_path: "/scratch/hdd001/home/jennybao/projects/LTE/dummy_models"
  root_path: "./test_exp"
  experiment_name: "mimic"
  load_version: "auto_resume"

trainer:
  <type>: Trainer
  <init>: false
  max_epochs: 10000

# Seed.
seed: 0
